//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureTestWebDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_annooli_231161891
    {
        public int RowId { get; set; }
        public string Pricing_Level { get; set; }
        public string Business_Summary { get; set; }
        public string Future_Flag { get; set; }
        public string Fiscal_Month { get; set; }
        public Nullable<decimal> MS_Sales_Amount_Const { get; set; }
    }
}
